// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdzDH8v1PPNVlmY_HehS3FztNrxZsa9Uk',
    appId: '1:186844623282:web:8c2f155fdf43f03fd334ab',
    messagingSenderId: '186844623282',
    projectId: 'bebepaca-55ee0',
    authDomain: 'bebepaca-55ee0.firebaseapp.com',
    storageBucket: 'bebepaca-55ee0.appspot.com',
    measurementId: 'G-Y62FP8RQX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtUW3PdpNMXEqE6XajPFpcYFAQmp_oJ20',
    appId: '1:186844623282:android:33cde6f76cc2a90cd334ab',
    messagingSenderId: '186844623282',
    projectId: 'bebepaca-55ee0',
    storageBucket: 'bebepaca-55ee0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmyDxVIG7DrilH9frIBANqwHHycGefP_E',
    appId: '1:186844623282:ios:d4dca45bc60cd83fd334ab',
    messagingSenderId: '186844623282',
    projectId: 'bebepaca-55ee0',
    storageBucket: 'bebepaca-55ee0.appspot.com',
    iosClientId: '186844623282-fg6j7cs7i1b806lrnoaff6ofh0ejekq6.apps.googleusercontent.com',
    iosBundleId: 'com.bebepaca.bebepaca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmyDxVIG7DrilH9frIBANqwHHycGefP_E',
    appId: '1:186844623282:ios:d4dca45bc60cd83fd334ab',
    messagingSenderId: '186844623282',
    projectId: 'bebepaca-55ee0',
    storageBucket: 'bebepaca-55ee0.appspot.com',
    iosClientId: '186844623282-fg6j7cs7i1b806lrnoaff6ofh0ejekq6.apps.googleusercontent.com',
    iosBundleId: 'com.bebepaca.bebepaca',
  );
}
